apiVersion: metro.digital/v1
kind: KGCPSecret
metadata:
  namespace: my-namespace         # optional (K8S namespace)
  name: my-k8s-secret             # mandatory (K8S secret name)
  environment: prod               # optional (identifier of environment)
  stage:                          # deprecated (will be overwritten by 'environment')
  tag:                            # optional (can be used for additional structuring)
  dc:                             # deprecated (will be overwritten by 'tag')
  labels:                         # optional (will go into K8S secret)
    - label1: value1
    - label2: value2
  annotations:                    # optional (will go into K8S secret)
    - annotation1: do-this
    - annotation2: do-that
gcpProjectID: gcp-project-id      # GCP project id
dataType: envvar                  # optional, default null/as a file (Define your secret data as envvar)
disableNameSuffixHash: false      # optional (Should kustomize create hash into secret name)
type: opaque                      # optional (Type of the K8S secret)
behavior: merge                   # optional (Kustomize behaviour during processing)
keys:
- db-user                         # (base) id of the secret in Google Secret Manger
- db-password                     # lookup of value will happen with pre- and postfix combinations
